(function () {
  // --- What kind of page is this? ---
  // Post pages (/p/<slug>/) are generated by build.js and announce themselves
  // with window.__POST__. Everything else is a landing page (/ or /ko/) that
  // renders the post list. One file serves both; the blocks below are guarded
  // on the elements they need, so each page only runs what applies to it.
  var POST = window.__POST__ || null;

  // Posts used to live at /#p/<slug> on the landing page. Those links are out
  // in the wild (published RSS items, anything already shared), so honour them
  // by redirecting to the real page. replace() rather than assign() keeps the
  // dead hash URL out of the back history.
  function redirectLegacyHash() {
    var legacy = location.hash.match(/^#p\/(.+)$/);
    if (!legacy) return false;
    location.replace('/p/' + encodeURIComponent(decodeURIComponent(legacy[1])) + '/');
    return true;
  }

  if (!POST) {
    // On a fresh load (the RSS/bookmark case) this runs before anything is
    // rendered. The hashchange listener covers the rarer same-document case,
    // where the browser changes only the fragment and never re-runs this file.
    if (redirectLegacyHash()) return;
    window.addEventListener('hashchange', redirectLegacyHash);
  }

  // --- i18n ---
  // The Korean page (ko/index.html) sets <html lang="ko">; everything else
  // sets lang="en" (or omits it). Chrome strings this file writes into the
  // DOM look themselves up here instead of being hardcoded, so main.js stays
  // a single shared file across both pages.
  var LOCALE = document.documentElement.lang === 'ko' ? 'ko' : 'en';
  // Deliberately narrow: only generic UI verbs/microcopy (search, filters,
  // loading/error states, pagination) are localized. Names, titles, and body
  // copy stay in their original language on both pages — see the ko/index.html
  // and projects.js/experiences.js comments for the reasoning.
  var STRINGS = {
    en: {
      viewDemo: 'View Demo', viewCode: 'View Code',
      searchPlaceholder: 'Search posts (title + content)…', searchAria: 'Search posts',
      all: 'All', noResults: 'No posts match your search.', readMore: 'Read more →',
      showMore: 'Show more',
      loading: 'Loading…', invalidPost: 'Invalid post.', loadError: 'Could not load this post.',
      openMenu: 'Open menu', closeMenu: 'Close menu',
    },
    ko: {
      viewDemo: '데모 보기', viewCode: '코드 보기',
      searchPlaceholder: '글 검색 (제목 + 본문)…', searchAria: '글 검색',
      all: '전체', noResults: '검색 결과와 일치하는 글이 없습니다.', readMore: '더 읽기 →',
      showMore: '더 보기',
      loading: '불러오는 중…', invalidPost: '잘못된 글입니다.', loadError: '글을 불러올 수 없습니다.',
      openMenu: '메뉴 열기', closeMenu: '메뉴 닫기',
    },
  };
  function t(key) { return STRINGS[LOCALE][key]; }

  // --- Dark mode toggle ---
  var HLJS_LIGHT = 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/github.min.css';
  var HLJS_DARK  = 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/github-dark.min.css';

  // --- On-demand loading of post-rendering libraries (marked / KaTeX / highlight.js) ---
  // These are only needed when a post is opened, so we keep them off the initial page load.
  var postLibsPromise = null;

  function loadScriptOnce(src) {
    return new Promise(function (resolve, reject) {
      var s = document.createElement('script');
      s.src = src;
      s.async = true;
      s.onload = resolve;
      s.onerror = function () { reject(new Error('Failed to load ' + src)); };
      document.head.appendChild(s);
    });
  }

  function loadStyleOnce(href, id) {
    return new Promise(function (resolve) {
      var l = document.createElement('link');
      l.rel = 'stylesheet';
      l.href = href;
      if (id) l.id = id;
      l.onload = resolve;
      l.onerror = resolve; // a missing stylesheet shouldn't block rendering
      document.head.appendChild(l);
    });
  }

  function ensurePostLibs() {
    if (postLibsPromise) return postLibsPromise;
    var isDark = document.documentElement.getAttribute('data-theme') === 'dark';
    postLibsPromise = Promise.all([
      // Pinned deliberately. The unversioned URL used to sit here, which meant
      // every reader got whatever jsdelivr's edge cache happened to hold — at
      // the time of pinning that was 15.0.12 while npm "latest" was 18.0.9, so
      // the site had already drifted three majors behind without anyone
      // noticing, and a cache refresh could have swapped the markdown renderer
      // under all 65 posts with no deploy. 15.0.12 is the version this site
      // has been rendering with and the one every post was verified against;
      // upgrading is a separate, testable change.
      loadScriptOnce('https://cdn.jsdelivr.net/npm/marked@15.0.12/marked.min.js'),
      loadStyleOnce('https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css'),
      loadScriptOnce('https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js'),
      loadStyleOnce(isDark ? HLJS_DARK : HLJS_LIGHT, 'hljs-theme'),
      loadScriptOnce('https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js')
    ]);
    return postLibsPromise;
  }

  function applyTheme(dark) {
    document.documentElement.setAttribute('data-theme', dark ? 'dark' : 'light');
    var link = document.getElementById('hljs-theme');
    if (link) link.href = dark ? HLJS_DARK : HLJS_LIGHT;
  }

  var themeToggle = document.getElementById('theme-toggle');
  if (themeToggle) {
    themeToggle.addEventListener('click', function () {
      var isDark = document.documentElement.getAttribute('data-theme') === 'dark';
      applyTheme(!isDark);
      localStorage.setItem('theme', !isDark ? 'dark' : 'light');
    });
  }

  const navLinks = document.querySelectorAll('.nav-link');
  const sections = document.querySelectorAll('.section');

  function setActiveNav(sectionId) {
    navLinks.forEach(function (link) {
      var isActive = link.getAttribute('data-section') === sectionId;
      link.classList.toggle('active', isActive);
      // The class alone is invisible to assistive tech; aria-current is what
      // actually announces "you are here".
      if (isActive) link.setAttribute('aria-current', 'true');
      else link.removeAttribute('aria-current');
    });
  }

  function onNavClick(e) {
    const link = e.currentTarget;
    const sectionId = link.getAttribute('data-section');
    if (!sectionId) return;
    const section = document.getElementById(sectionId);
    if (section) {
      section.scrollIntoView({ behavior: 'smooth', block: 'start' });
      setActiveNav(sectionId);
      hideTOC();
    }
    closeMenu();
  }

  // --- Mobile hamburger menu ---
  var navToggle = document.getElementById('nav-toggle');
  var primaryNav = document.getElementById('primary-nav');

  function closeMenu() {
    if (!navToggle || !primaryNav) return;
    primaryNav.classList.remove('open');
    navToggle.setAttribute('aria-expanded', 'false');
    navToggle.setAttribute('aria-label', t('openMenu'));
  }

  function openMenu() {
    if (!navToggle || !primaryNav) return;
    primaryNav.classList.add('open');
    navToggle.setAttribute('aria-expanded', 'true');
    navToggle.setAttribute('aria-label', t('closeMenu'));
  }

  if (navToggle && primaryNav) {
    navToggle.addEventListener('click', function (e) {
      e.stopPropagation();
      if (primaryNav.classList.contains('open')) closeMenu();
      else openMenu();
    });
    document.addEventListener('click', function (e) {
      if (!primaryNav.classList.contains('open')) return;
      if (primaryNav.contains(e.target) || navToggle.contains(e.target)) return;
      closeMenu();
    });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') closeMenu();
    });
  }

  // Set by setupReadingControls() on post pages; stays null on landing pages,
  // where there is no single article to measure progress through.
  var updateReadingControls = null;

  function onScroll() {
    var headerEl = document.querySelector('.header');
    if (headerEl) headerEl.classList.toggle('scrolled', window.scrollY > 8);
    // A post page has no nav sections to spy on, and its TOC is shown by
    // buildTOC and then simply stays put — nothing here should touch it.
    if (POST) {
      if (updateReadingControls) updateReadingControls();
      return;
    }
    const headerHeight = headerEl ? headerEl.offsetHeight : 0;
    let current = 'home';
    sections.forEach(function (section) {
      const top = section.getBoundingClientRect().top;
      if (top <= headerHeight + 50) {
        current = section.id;
      }
    });
    setActiveNav(current);
  }

  navLinks.forEach(function (link) {
    link.addEventListener('click', onNavClick);
  });

  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();

  // Render projects from projects.js
  //
  // Featured entries render first and full-width with their metric set large;
  // everything else keeps the existing card. Sorting here rather than in
  // projects.js means the data file stays in Ricky's preferred reading order
  // and the emphasis is a presentation decision. Array.prototype.sort is
  // stable in every engine this targets, so entries with equal `featured` keep
  // their authored order.
  if (typeof projects !== 'undefined') {
    const grid = document.getElementById('projects-grid');
    if (grid) {
      var ordered = projects.slice().sort(function (a, b) {
        return (b.featured ? 1 : 0) - (a.featured ? 1 : 0);
      });

      grid.innerHTML = ordered
        .map(function (p) {
          var tagsHtml = (p.tags || [])
            .map(function (tag) {
              return '<span class="tag">' + escapeHtml(tag) + '</span>';
            })
            .join('');
          // Project titles/descriptions are not translated — see projects.js.
          var hasDemo = p.link && p.link !== '#';
          var demoLabel = (p.linkLabel && p.linkLabel.trim()) ? p.linkLabel.trim() : t('viewDemo');
          var linksHtml =
            (hasDemo
              ? '<a href="' + escapeAttr(p.link) + '" class="card-link" target="_blank" rel="noopener noreferrer">' + escapeHtml(demoLabel) + '</a>'
              : '') +
            '<a href="' + escapeAttr(p.codeLink || '#') + '" class="card-link" target="_blank" rel="noopener noreferrer">' + escapeHtml(t('viewCode')) + '</a>';

          var metricHtml = '';
          if (p.metric && p.metric.value) {
            metricHtml = p.featured
              ? '<div class="card-metric">' +
                  '<span class="card-metric-value">' + escapeHtml(p.metric.value) + '</span>' +
                  '<span class="card-metric-label">' + escapeHtml(p.metric.label || '') + '</span>' +
                '</div>'
              : '<p class="card-metric-inline">' +
                  '<strong>' + escapeHtml(p.metric.value) + '</strong> ' +
                  escapeHtml(p.metric.label || '') +
                '</p>';
          }

          if (p.featured) {
            return (
              '<article class="card card-featured">' +
              '<div class="card-featured-body">' +
              '<h3 class="card-title">' + escapeHtml(p.title) + '</h3>' +
              '<p class="card-desc">' + escapeHtml(p.description) + '</p>' +
              '<div class="card-tags">' + tagsHtml + '</div>' +
              '<div class="card-links">' + linksHtml + '</div>' +
              '</div>' +
              metricHtml +
              '</article>'
            );
          }

          return (
            '<article class="card">' +
            '<h3 class="card-title">' + escapeHtml(p.title) + '</h3>' +
            '<p class="card-desc">' + escapeHtml(p.description) + '</p>' +
            metricHtml +
            '<div class="card-tags">' + tagsHtml + '</div>' +
            '<div class="card-links">' + linksHtml + '</div>' +
            '</article>'
          );
        })
        .join('');
    }
  }

  // --- Obsidian-compatible markdown helpers ---

  function headingToSlug(text) {
    return String(text)
      .trim()
      .normalize('NFKC')
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^\p{L}\p{N}\-_]/gu, '');
  }

  function preprocessObsidian(md, baseDir) {
    baseDir = baseDir || '';
    md = md.replace(/^---[\s\S]*?---\n?/, '');

    var codeStore = [];
    var mathStore = [];

    var lines = md.split('\n');
    var out = [];
    var inFence = '';
    var fenceBuf = [];
    var fencePrefix = '';

    for (var li = 0; li < lines.length; li++) {
      var line = lines[li];
      var pm = line.match(/^((?:>\s?)*)/);
      var prefix = pm ? pm[1] : '';
      var content = line.slice(prefix.length);

      if (!inFence && /^```/.test(content)) {
        inFence = 'code';
        fencePrefix = prefix;
        fenceBuf = [content];
      } else if (inFence === 'code' && /^```\s*$/.test(content)) {
        fenceBuf.push(content);
        inFence = '';
        codeStore.push({ text: fenceBuf.join('\n'), prefix: fencePrefix });
        out.push(fencePrefix + '%%CODE' + (codeStore.length - 1) + '%%');
        fenceBuf = [];
      } else if (!inFence && /^\$\$\s*$/.test(content)) {
        inFence = 'math';
        fencePrefix = prefix;
        fenceBuf = [];
      } else if (inFence === 'math' && /^\$\$\s*$/.test(content)) {
        inFence = '';
        mathStore.push({ tex: fenceBuf.join('\n').trim(), display: true });
        out.push(fencePrefix + '%%MATH' + (mathStore.length - 1) + '%%');
      } else if (inFence) {
        fenceBuf.push(content);
      } else {
        out.push(line);
      }
    }
    if (inFence === 'code') {
      for (var fi = 0; fi < fenceBuf.length; fi++) out.push(fencePrefix + fenceBuf[fi]);
    } else if (inFence === 'math') {
      out.push(fencePrefix + '$$');
      for (var mi = 0; mi < fenceBuf.length; mi++) out.push(fencePrefix + fenceBuf[mi]);
      out.push(fencePrefix + '$$');
    }

    md = out.join('\n');

    md = md.replace(/`([^`\n]+?)`/g, function (m) {
      codeStore.push({ text: m, prefix: '' });
      return '%%CODE' + (codeStore.length - 1) + '%%';
    });

    md = md.replace(/\$\$([\s\S]+?)\$\$/g, function (m, tex) {
      tex = tex.replace(/^>\s?/gm, '').trim();
      mathStore.push({ tex: tex, display: true });
      return '\n\n%%MATH' + (mathStore.length - 1) + '%%\n\n';
    });
    md = md.replace(/\$([^\$\n]+?)\$/g, function (m, tex) {
      mathStore.push({ tex: tex, display: false });
      return '%%MATH' + (mathStore.length - 1) + '%%';
    });

    md = md.replace(/==(.*?)==/g, '%%MARK_START%%$1%%MARK_END%%');

    md = md.replace(/!\[\[([^\]|]+?)(?:\|([^\]]*))?\]\]/g, function (m, file, dims) {
      // Obsidian normally writes embed targets as a bare filename, but falls
      // back to a full vault-relative path when a filename collides with
      // another attachment elsewhere in the vault (e.g. "week 10.md" has
      // "🐻 UC Berkeley/.../attachments/image-4.png" instead of just
      // "image-4.png"). attachments/ here only ever holds files by their
      // bare name (see sync.js copyDirSync), so resolve on the basename
      // regardless of which form Obsidian wrote.
      var name = file.trim().split('/').pop();
      var src = baseDir + 'attachments/' + name;
      var srcAttr = escapeAttr(src.replace(/ /g, '%20'));
      var altAttr = escapeAttr(name);
      if (!dims) return '![' + name + '](<' + src + '>)';
      var wh = dims.match(/^(\d+)x(\d+)$/);
      if (wh) {
        return '<img src="' + srcAttr + '" width="' + wh[1] + '" height="' + wh[2] +
          '" alt="' + altAttr + '" />';
      }
      // Obsidian's single-number form (|400) is a width. Anything else in that
      // slot is a caption or an alias, not a dimension — emitting it as a width
      // attribute would produce invalid HTML, so fall back to a plain image.
      if (/^\d+$/.test(dims.trim())) {
        return '<img src="' + srcAttr + '" width="' + dims.trim() + '" alt="' + altAttr + '" />';
      }
      return '<img src="' + srcAttr + '" alt="' + altAttr + '" />';
    });

    md = md.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, function (m, alt, url) {
      if (url.indexOf(' ') === -1 || url.charAt(0) === '<') return m;
      return '![' + alt + '](<' + url + '>)';
    });

    md = md.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, function (m, target, alias) {
      target = target.trim();
      if (target.charAt(0) === '#') {
        var headingText = target.slice(1).trim();
        if (headingText.charAt(0) === '^') return alias || target;
        var label = alias || headingText;
        var slug = headingToSlug(headingText);
        return '[' + label + '](#' + slug + ')';
      }
      return alias || target;
    });

    md = md.replace(/%%CODE(\d+)%%/g, function (m, idx) {
      var stored = codeStore[parseInt(idx, 10)];
      if (!stored) return m;
      if (!stored.prefix) return stored.text;
      var cl = stored.text.split('\n');
      return cl[0] + (cl.length > 1 ? '\n' + cl.slice(1).map(function (l) { return stored.prefix + l; }).join('\n') : '');
    });

    var footnoteResult = extractFootnotes(md);
    return { md: footnoteResult.md, mathStore: mathStore, footnotes: footnoteResult.footnotes };
  }

  function footnoteSlug(id) {
    return String(id).replace(/[^a-zA-Z0-9_-]/g, '-');
  }

  function extractFootnotes(md) {
    var definitions = {};
    var order = [];
    var lines = md.split('\n');
    var out = [];
    var i = 0;

    while (i < lines.length) {
      var line = lines[i];
      var prefixMatch = line.match(/^((?:>\s?)*)/);
      var prefix = prefixMatch ? prefixMatch[1] : '';
      var content = line.slice(prefix.length);
      var defMatch = content.match(/^\[\^([^\]]+)\]:\s?(.*)$/);

      if (defMatch) {
        var id = defMatch[1];
        var body = [defMatch[2]];
        i++;
        while (i < lines.length) {
          var next = lines[i];
          var nextPrefixMatch = next.match(/^((?:>\s?)*)/);
          var nextPrefix = nextPrefixMatch ? nextPrefixMatch[1] : '';
          var nextContent = next.slice(nextPrefix.length);
          if (/^\[\^[^\]]+\]:/.test(nextContent)) break;
          if (/^(?:\t| {4})/.test(nextContent)) {
            body.push(nextContent.replace(/^(?:\t| {4})/, ''));
            i++;
          } else {
            break;
          }
        }
        if (!definitions[id]) order.push(id);
        definitions[id] = body.join('\n').trim();
        continue;
      }

      out.push(line);
      i++;
    }

    if (order.length === 0) return { md: md, footnotes: null };

    order.forEach(function (id) {
      var escapedId = id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      out = out.map(function (line) {
        return line.replace(new RegExp('\\[\\^' + escapedId + '\\]', 'g'), '%%FNREF:' + id + '%%');
      });
    });

    return { md: out.join('\n'), footnotes: { definitions: definitions, order: order } };
  }

  function restoreFootnotes(html, footnotes) {
    if (!footnotes) return html;

    footnotes.order.forEach(function (id, idx) {
      var num = idx + 1;
      var fnId = 'fn-' + footnoteSlug(id);
      var refId = 'fnref-' + footnoteSlug(id);
      var refHtml = '<sup class="footnote-ref"><a href="#' + fnId + '" id="' + refId + '">' + num + '</a></sup>';
      html = html.split('%%FNREF:' + id + '%%').join(refHtml);
    });

    var items = footnotes.order.map(function (id, idx) {
      var num = idx + 1;
      var fnId = 'fn-' + footnoteSlug(id);
      var refId = 'fnref-' + footnoteSlug(id);
      var body = marked.parse(footnotes.definitions[id] || '');
      return '<li id="' + fnId + '">' + body +
        ' <a href="#' + refId + '" class="footnote-backref" aria-label="Back to reference ' + num + '">↩</a>' +
        '</li>';
    }).join('');

    html += '<section class="footnotes" aria-label="Footnotes"><hr class="footnotes-sep">' +
      '<ol class="footnotes-list">' + items + '</ol></section>';
    return html;
  }

  var footnotePreviewEl = null;
  var footnotePreviewHideTimer = null;
  var footnotePreviewScrollBound = false;

  function hideFootnotePreview() {
    if (footnotePreviewHideTimer) {
      clearTimeout(footnotePreviewHideTimer);
      footnotePreviewHideTimer = null;
    }
    if (!footnotePreviewEl) return;
    footnotePreviewEl.hidden = true;
    footnotePreviewEl.innerHTML = '';
    footnotePreviewEl.removeAttribute('data-anchor-id');
  }

  function ensureFootnotePreviewElement() {
    if (footnotePreviewEl) return footnotePreviewEl;
    footnotePreviewEl = document.createElement('div');
    footnotePreviewEl.id = 'footnote-preview';
    footnotePreviewEl.className = 'footnote-preview';
    footnotePreviewEl.setAttribute('role', 'tooltip');
    footnotePreviewEl.hidden = true;
    document.body.appendChild(footnotePreviewEl);

    footnotePreviewEl.addEventListener('mouseenter', function () {
      if (footnotePreviewHideTimer) {
        clearTimeout(footnotePreviewHideTimer);
        footnotePreviewHideTimer = null;
      }
    });
    footnotePreviewEl.addEventListener('mouseleave', function () {
      footnotePreviewHideTimer = setTimeout(hideFootnotePreview, 120);
    });

    if (!footnotePreviewScrollBound) {
      footnotePreviewScrollBound = true;
      window.addEventListener('scroll', hideFootnotePreview, { passive: true, capture: true });
      window.addEventListener('resize', hideFootnotePreview, { passive: true });
    }
    return footnotePreviewEl;
  }

  function positionFootnotePreview(anchor, popover) {
    var rect = anchor.getBoundingClientRect();
    var popRect = popover.getBoundingClientRect();
    var gap = 8;
    var margin = 12;
    var top = rect.bottom + gap;
    var left = rect.left + rect.width / 2 - popRect.width / 2;

    left = Math.max(margin, Math.min(left, window.innerWidth - popRect.width - margin));

    if (top + popRect.height > window.innerHeight - margin) {
      top = rect.top - popRect.height - gap;
    }
    if (top < margin) {
      top = margin;
    }

    popover.style.top = top + 'px';
    popover.style.left = left + 'px';
  }

  function showFootnotePreview(anchor, body) {
    if (!anchor || !body) return;
    var href = anchor.getAttribute('href') || '';
    if (href.charAt(0) !== '#') return;
    var fnId = href.slice(1);
    var fnEl = body.querySelector('#' + CSS.escape(fnId));
    if (!fnEl) return;

    var popover = ensureFootnotePreviewElement();
    var num = anchor.textContent.trim();
    var content = fnEl.cloneNode(true);
    var backref = content.querySelector('.footnote-backref');
    if (backref) backref.remove();

    popover.innerHTML =
      '<div class="footnote-preview-label">' + escapeHtml(num) + '</div>' +
      '<div class="footnote-preview-body">' + content.innerHTML + '</div>';

    popover.hidden = false;
    popover.style.visibility = 'hidden';
    positionFootnotePreview(anchor, popover);
    popover.style.visibility = '';
    popover.setAttribute('data-anchor-id', fnId);
  }

  function setupFootnotePreviews(body) {
    if (!body) return;
    var refs = body.querySelectorAll('.footnote-ref a[href^="#fn-"]');
    if (!refs.length) return;

    var supportsHover = window.matchMedia('(hover: hover) and (pointer: fine)').matches;

    refs.forEach(function (anchor) {
      anchor.setAttribute('aria-describedby', 'footnote-preview');

      if (supportsHover) {
        anchor.addEventListener('mouseenter', function () {
          if (footnotePreviewHideTimer) {
            clearTimeout(footnotePreviewHideTimer);
            footnotePreviewHideTimer = null;
          }
          showFootnotePreview(anchor, body);
        });
        anchor.addEventListener('mouseleave', function (e) {
          var related = e.relatedTarget;
          if (related && footnotePreviewEl && footnotePreviewEl.contains(related)) return;
          footnotePreviewHideTimer = setTimeout(hideFootnotePreview, 120);
        });
      }

      anchor.addEventListener('focus', function () {
        if (footnotePreviewHideTimer) {
          clearTimeout(footnotePreviewHideTimer);
          footnotePreviewHideTimer = null;
        }
        showFootnotePreview(anchor, body);
      });
      anchor.addEventListener('blur', function () {
        footnotePreviewHideTimer = setTimeout(hideFootnotePreview, 120);
      });
    });
  }

  function restoreMathAndMarks(html, mathStore) {
    if (!mathStore) return html;
    html = html.replace(/%%MATH(\d+)%%/g, function (m, idx) {
      var item = mathStore[parseInt(idx, 10)];
      if (!item) return m;
      if (item.display) {
        return '<div class="math-display" data-math="' + encodeURIComponent(item.tex) + '"></div>';
      }
      return '<span class="math-inline" data-math="' + encodeURIComponent(item.tex) + '"></span>';
    });
    html = html.replace(/%%MARK_START%%/g, '<mark>');
    html = html.replace(/%%MARK_END%%/g, '</mark>');
    return html;
  }

  function assignHeadingIds(container) {
    if (!container) return;
    var used = {};
    container.querySelectorAll('h1, h2, h3, h4, h5, h6').forEach(function (h) {
      if (h.closest('.footnotes')) return;
      var base = headingToSlug(h.textContent);
      if (!base) return;
      var slug = base;
      if (used[base]) {
        slug = base + '-' + used[base];
        used[base]++;
      } else {
        used[base] = 1;
      }
      h.id = slug;
    });
  }

  function scrollToElement(el) {
    if (!el) return;
    var headerH = 80;
    var top = el.getBoundingClientRect().top + window.scrollY - headerH - 12;
    window.scrollTo({ top: Math.max(0, top), behavior: 'smooth' });
  }

  function setupInternalLinks(body) {
    if (!body) return;
    body.querySelectorAll('a[href^="#"]').forEach(function (a) {
      a.classList.add('internal-link');
      a.addEventListener('click', function (e) {
        var raw = a.getAttribute('href').slice(1);
        if (!raw) return;
        var id = decodeURIComponent(raw);
        var target = document.getElementById(id);
        if (!target && body.querySelector) {
          target = body.querySelector('[id="' + id.replace(/"/g, '\\"') + '"]');
        }
        if (target) {
          e.preventDefault();
          scrollToElement(target);
          if (history.replaceState) {
            history.replaceState(null, '', '#' + encodeURIComponent(id));
          }
        }
      });
    });
  }

  function transformCallouts(container) {
    if (!container) return;
    container.querySelectorAll('blockquote').forEach(function (bq) {
      var firstP = bq.querySelector('p');
      if (!firstP) return;

      var html = firstP.innerHTML;
      var match = html.match(/^\s*\[!([\w-]+)\]([+-]?)\s*/);
      if (!match) return;

      var type = match[1].toLowerCase();
      var afterMatch = html.slice(match[0].length);
      var breakIdx = afterMatch.search(/\n|<br\s*\/?>/i);
      var title, remaining;

      if (breakIdx >= 0) {
        title = afterMatch.substring(0, breakIdx).trim();
        remaining = afterMatch.substring(breakIdx).replace(/^(\n|<br\s*\/?>)/i, '').trim();
      } else {
        title = afterMatch.trim();
        remaining = '';
      }

      if (!title) title = type.charAt(0).toUpperCase() + type.slice(1);

      var contentDiv = document.createElement('div');
      contentDiv.className = 'callout-content';
      var hasContent = false;

      if (remaining) {
        var p = document.createElement('p');
        p.innerHTML = remaining;
        contentDiv.appendChild(p);
        hasContent = true;
      }

      while (bq.children.length > 0) {
        var child = bq.children[0];
        if (child === firstP) { bq.removeChild(child); continue; }
        contentDiv.appendChild(child);
        hasContent = true;
      }

      var callout = document.createElement('div');
      callout.className = 'callout callout-' + type;

      var startCollapsed = match[2] === '-';
      if (hasContent && startCollapsed) callout.classList.add('callout-collapsed');

      var titleEl = document.createElement(hasContent ? 'button' : 'div');
      titleEl.className = 'callout-title';
      if (hasContent) {
        titleEl.type = 'button';
        titleEl.setAttribute('aria-expanded', startCollapsed ? 'false' : 'true');
        titleEl.innerHTML =
          '<svg class="callout-chevron" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="6 9 12 15 18 9"/></svg>' +
          '<span class="callout-title-text">' + title + '</span>';
        titleEl.addEventListener('click', function () {
          var collapsed = callout.classList.toggle('callout-collapsed');
          titleEl.setAttribute('aria-expanded', collapsed ? 'false' : 'true');
        });
      } else {
        titleEl.innerHTML = title;
      }
      callout.appendChild(titleEl);

      if (hasContent) callout.appendChild(contentDiv);
      bq.parentNode.replaceChild(callout, bq);
    });
  }

  function renderMath(container) {
    if (typeof katex === 'undefined' || !container) return;

    container.querySelectorAll('.math-display').forEach(function (el) {
      var raw = el.getAttribute('data-math');
      if (raw == null) return;
      try {
        katex.render(decodeURIComponent(raw), el, {
          displayMode: true, throwOnError: false
        });
      } catch (e) { /* fallback: raw tex stays visible */ }
    });

    container.querySelectorAll('.math-inline').forEach(function (el) {
      var raw = el.getAttribute('data-math');
      if (raw == null) return;
      try {
        katex.render(decodeURIComponent(raw), el, {
          displayMode: false, throwOnError: false
        });
      } catch (e) { /* fallback: raw tex stays visible */ }
    });
  }

  // --- Table of Contents ---

  var tocEl = document.getElementById('writing-toc');
  var tocInlineEl = document.getElementById('writing-toc-inline');
  var tocScrollHandler = null;
  var tocInlineChevronSvg = '<svg class="toc-inline-chevron" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="6 9 12 15 18 9"/></svg>';

  function showTOC() { if (tocEl) tocEl.classList.add('visible'); }
  function hideTOC() { if (tocEl) tocEl.classList.remove('visible'); }

  var tocBackBtnHtml = '<a class="writing-back-btn writing-back-btn-toc" href="/#writings">&larr; Back to list</a>';
  var tocChevronSvg = '<svg class="toc-chevron" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="6 9 12 15 18 9"/></svg>';

  function buildTOCTree(headings) {
    var root = { level: 0, children: [] };
    var stack = [root];

    headings.forEach(function (h) {
      var level = parseInt(h.tagName[1], 10);
      var node = { heading: h, level: level, children: [] };

      while (stack.length > 1 && stack[stack.length - 1].level >= level) {
        stack.pop();
      }
      stack[stack.length - 1].children.push(node);
      stack.push(node);
    });

    return root.children;
  }

  function renderTOCNodes(nodes) {
    if (!nodes.length) return '';
    var html = '<ul class="toc-list">';
    nodes.forEach(function (node) {
      var hasChildren = node.children.length > 0;
      html += '<li class="toc-item toc-level-' + node.level + (hasChildren ? ' toc-has-children' : '') + '">';
      html += '<div class="toc-row">';
      if (hasChildren) {
        html += '<button type="button" class="toc-toggle" aria-expanded="true" aria-label="Toggle section">' +
          tocChevronSvg + '</button>';
      } else {
        html += '<span class="toc-toggle-spacer" aria-hidden="true"></span>';
      }
      html += '<a class="toc-link" href="#' + escapeAttr(node.heading.id) + '">' +
        escapeHtml(node.heading.textContent) + '</a>';
      html += '</div>';
      if (hasChildren) {
        html += '<div class="toc-children-wrap">' + renderTOCNodes(node.children) + '</div>';
      }
      html += '</li>';
    });
    html += '</ul>';
    return html;
  }

  function buildTOC(body) {
    if (!tocEl || !body) return;
    var allHeadings = body.querySelectorAll('h1, h2, h3, h4');
    var headings = Array.prototype.filter.call(allHeadings, function (h) {
      return !h.closest('.callout');
    });
    if (headings.length < 2) {
      tocEl.innerHTML = tocBackBtnHtml;
      if (tocInlineEl) tocInlineEl.innerHTML = '';
      showTOC();
      return;
    }

    headings.forEach(function (h, i) {
      if (!h.id) h.id = 'heading-' + i;
    });

    var tree = buildTOCTree(headings);
    var html = '<div class="toc-title">Contents</div>' + renderTOCNodes(tree) + tocBackBtnHtml;
    tocEl.innerHTML = html;

    tocEl.querySelectorAll('.toc-toggle').forEach(function (btn) {
      btn.addEventListener('click', function (e) {
        e.preventDefault();
        e.stopPropagation();
        var item = btn.closest('.toc-item');
        if (!item) return;
        var expanded = btn.getAttribute('aria-expanded') === 'true';
        btn.setAttribute('aria-expanded', expanded ? 'false' : 'true');
        item.classList.toggle('toc-collapsed', expanded);
      });
    });

    var links = tocEl.querySelectorAll('.toc-link');
    links.forEach(function (a) {
      a.addEventListener('click', function (e) {
        e.preventDefault();
        var target = document.getElementById(a.getAttribute('href').slice(1));
        if (target) scrollToElement(target);
      });
    });

    // Inline TOC for mobile (≤1200px)
    var inlineLinks = [];
    if (tocInlineEl) {
      var inlineHtml = '<button type="button" class="toc-inline-toggle" aria-expanded="false">' +
        '<span class="toc-inline-title">Contents</span>' + tocInlineChevronSvg + '</button>' +
        '<div class="toc-inline-body" hidden>' + renderTOCNodes(tree) + '</div>';
      tocInlineEl.innerHTML = inlineHtml;

      var inlineToggleBtn = tocInlineEl.querySelector('.toc-inline-toggle');
      var inlineBody = tocInlineEl.querySelector('.toc-inline-body');
      inlineToggleBtn.addEventListener('click', function () {
        var expanded = inlineToggleBtn.getAttribute('aria-expanded') === 'true';
        inlineToggleBtn.setAttribute('aria-expanded', expanded ? 'false' : 'true');
        inlineBody.hidden = expanded;
      });

      tocInlineEl.querySelectorAll('.toc-toggle').forEach(function (btn) {
        btn.addEventListener('click', function (e) {
          e.preventDefault();
          e.stopPropagation();
          var item = btn.closest('.toc-item');
          if (!item) return;
          var expanded = btn.getAttribute('aria-expanded') === 'true';
          btn.setAttribute('aria-expanded', expanded ? 'false' : 'true');
          item.classList.toggle('toc-collapsed', expanded);
        });
      });

      inlineLinks = Array.prototype.slice.call(tocInlineEl.querySelectorAll('.toc-link'));
      inlineLinks.forEach(function (a) {
        a.addEventListener('click', function (e) {
          e.preventDefault();
          var target = document.getElementById(a.getAttribute('href').slice(1));
          if (target) scrollToElement(target);
          inlineToggleBtn.setAttribute('aria-expanded', 'false');
          inlineBody.hidden = true;
        });
      });
    }

    if (tocScrollHandler) window.removeEventListener('scroll', tocScrollHandler);
    tocScrollHandler = function () {
      var headerH = 80;
      var activeIdx = 0;
      for (var i = 0; i < headings.length; i++) {
        if (headings[i].getBoundingClientRect().top <= headerH + 20) activeIdx = i;
      }
      links.forEach(function (a, j) {
        a.classList.toggle('active', j === activeIdx);
      });
      inlineLinks.forEach(function (a, j) {
        a.classList.toggle('active', j === activeIdx);
      });

      var activeLink = links[activeIdx];
      if (activeLink) {
        var ancestor = activeLink.closest('.toc-item');
        while (ancestor) {
          if (ancestor.classList.contains('toc-collapsed')) {
            ancestor.classList.remove('toc-collapsed');
            var ancestorToggle = ancestor.querySelector(':scope > .toc-row > .toc-toggle');
            if (ancestorToggle) ancestorToggle.setAttribute('aria-expanded', 'true');
          }
          ancestor = ancestor.parentElement ? ancestor.parentElement.closest('.toc-item') : null;
        }
      }
    };
    window.addEventListener('scroll', tocScrollHandler, { passive: true });
    tocScrollHandler();
    showTOC();
  }

  function formatDate(dateStr) {
    if (dateStr == null || String(dateStr).trim() === '') return '';
    var d = new Date(dateStr + 'T00:00:00');
    if (Number.isNaN(d.getTime())) return '';
    return d.toLocaleDateString(LOCALE === 'ko' ? 'ko-KR' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  }

  /**
   * The page already shows the post title as its <h1> (build.js renders it into
   * the served HTML). Most notes repeat that title as a heading of their own,
   * which would print it twice and leave the page with two <h1>s — so drop the
   * body's copy when it matches. Notes whose title was assembled from several
   * headings (extractTitle joins them with " | ") match nothing and are left
   * alone, as are section headings that merely resemble the title.
   *
   * Also drops a rule at the very top of the body: several notes open with a
   * "****" separator, which lands directly under the post header's own border.
   */
  function dropRedundantLeadingElements(body) {
    while (body.firstElementChild && body.firstElementChild.tagName === 'HR') {
      body.removeChild(body.firstElementChild);
    }
    if (!POST || !POST.title) return;
    var wanted = POST.title.trim();
    var headings = body.querySelectorAll('h1');
    for (var i = 0; i < headings.length; i++) {
      if (headings[i].textContent.trim() === wanted) {
        headings[i].parentNode.removeChild(headings[i]);
        break;
      }
    }
    while (body.firstElementChild && body.firstElementChild.tagName === 'HR') {
      body.removeChild(body.firstElementChild);
    }
  }

  // --- Reading affordances (post pages only) ---

  /**
   * Wrap every table in a horizontally scrollable box.
   *
   * .writing-body table is width:100% with border-collapse:collapse and no
   * overflow rule of its own, unlike pre and .math-display. Cells refuse to
   * shrink below their content, so a wide table pushes the whole page sideways
   * on a phone. tabindex makes the box reachable by keyboard, which is what
   * lets a keyboard user scroll it at all.
   */
  function wrapTables(body) {
    body.querySelectorAll('table').forEach(function (table) {
      if (table.parentElement && table.parentElement.classList.contains('table-scroll')) return;
      var wrap = document.createElement('div');
      wrap.className = 'table-scroll';
      wrap.setAttribute('tabindex', '0');
      wrap.setAttribute('role', 'region');
      wrap.setAttribute('aria-label', 'Table');
      table.parentNode.insertBefore(wrap, table);
      wrap.appendChild(table);
    });
  }

  /**
   * Defer offscreen images and take them off the main thread's decode path.
   *
   * Applied in the DOM rather than in preprocessObsidian because images reach
   * the page by three different routes — the ![[embed]] rewrite, plain
   * markdown ![](), and raw <img> written straight into a note — and only the
   * rendered tree sees all three. Posts here run to dozens of screenshots, so
   * this is the difference between loading one image and loading forty.
   */
  function enhanceImages(body) {
    body.querySelectorAll('img').forEach(function (img) {
      if (!img.hasAttribute('loading')) img.setAttribute('loading', 'lazy');
      if (!img.hasAttribute('decoding')) img.setAttribute('decoding', 'async');
      // An image with no alt at all is invisible to a screen reader; the
      // filename is a poor description but it is better than nothing, and it
      // is what the author actually wrote.
      if (!img.hasAttribute('alt')) {
        var src = img.getAttribute('src') || '';
        try {
          img.setAttribute('alt', decodeURIComponent(src.split('/').pop() || ''));
        } catch (e) {
          img.setAttribute('alt', '');
        }
      }
    });
  }

  /**
   * Add a copy button to every code block.
   *
   * navigator.clipboard only exists on secure origins, so on plain http the
   * button is not rendered at all rather than rendered and dead. The text is
   * read from the <code> element before highlight.js markup is a concern —
   * textContent ignores the syntax spans and returns the original source.
   */
  function addCopyButtons(body) {
    if (!navigator.clipboard || !navigator.clipboard.writeText) return;
    body.querySelectorAll('pre').forEach(function (pre) {
      var code = pre.querySelector('code');
      if (!code || pre.querySelector('.code-copy-btn')) return;
      pre.classList.add('has-copy-btn');

      var btn = document.createElement('button');
      btn.type = 'button';
      btn.className = 'code-copy-btn';
      btn.setAttribute('aria-label', LOCALE === 'ko' ? '코드 복사' : 'Copy code');
      btn.textContent = LOCALE === 'ko' ? '복사' : 'Copy';

      btn.addEventListener('click', function () {
        navigator.clipboard.writeText(code.textContent).then(
          function () {
            btn.classList.add('copied');
            btn.textContent = LOCALE === 'ko' ? '복사됨' : 'Copied';
            setTimeout(function () {
              btn.classList.remove('copied');
              btn.textContent = LOCALE === 'ko' ? '복사' : 'Copy';
            }, 1600);
          },
          function (err) {
            // A rejected clipboard write is almost always a permissions
            // policy, not a bug in this code — say so rather than fail mute.
            btn.textContent = LOCALE === 'ko' ? '실패' : 'Failed';
            console.error('Clipboard write rejected:', err);
          }
        );
      });

      pre.appendChild(btn);
    });
  }

  /**
   * Append a permalink control to every heading that has an id.
   *
   * MUST run after buildTOC: the TOC reads h.textContent to build its labels,
   * so adding the anchor first would put a stray "#" at the end of every entry.
   * The visible glyph is aria-hidden and the accessible name comes from
   * aria-label, so a screen reader announces the heading rather than "number
   * sign" on every line.
   */
  function addHeadingAnchors(body) {
    body.querySelectorAll('h1[id], h2[id], h3[id], h4[id], h5[id], h6[id]').forEach(function (h) {
      if (h.closest('.footnotes') || h.querySelector('.heading-anchor')) return;
      var a = document.createElement('a');
      a.className = 'heading-anchor';
      a.href = '#' + encodeURIComponent(h.id);
      a.setAttribute('aria-label', (LOCALE === 'ko' ? '이 섹션 링크: ' : 'Link to this section: ') + h.textContent.trim());
      a.innerHTML = '<span aria-hidden="true">#</span>';
      a.addEventListener('click', function (e) {
        e.preventDefault();
        scrollToElement(h);
        if (history.replaceState) history.replaceState(null, '', '#' + encodeURIComponent(h.id));
      });
      h.appendChild(a);
    });
  }

  /**
   * Honour a fragment that was in the URL when the page loaded.
   *
   * Heading ids are assigned by assignHeadingIds *after* the markdown has been
   * fetched and parsed, which is long after the browser gave up looking for
   * the fragment — so pasting /p/<slug>/#some-heading into the address bar
   * used to land at the top of the post with no indication anything was wrong.
   * Called once at the end of the render pipeline.
   */
  function scrollToHashOnLoad() {
    if (!location.hash || location.hash.length < 2) return;
    var id;
    try {
      id = decodeURIComponent(location.hash.slice(1));
    } catch (e) {
      return; // a malformed fragment is not worth throwing over
    }
    var target = document.getElementById(id);
    if (!target) return;
    // Deliberately instant rather than scrollToElement's smooth scroll: this
    // fires once the body has rendered, and smoothly animating several
    // thousand pixels on arrival reads as the page running away from the
    // reader. A deep link should land, not travel.
    var top = target.getBoundingClientRect().top + window.scrollY - 80 - 12;
    window.scrollTo({ top: Math.max(0, top), behavior: 'auto' });
  }

  /**
   * Reading progress bar + back-to-top, both post-page only.
   *
   * Deliberately driven from the existing scroll listener rather than a second
   * one, and rAF-throttled because the progress calculation reads scrollHeight,
   * which forces a layout. Returns the per-scroll update function.
   */
  function setupReadingControls() {
    var bar = document.createElement('div');
    bar.className = 'reading-progress';
    bar.setAttribute('aria-hidden', 'true'); // decorative; the TOC conveys position
    bar.innerHTML = '<div class="reading-progress-fill"></div>';
    document.body.appendChild(bar);
    var fill = bar.firstElementChild;

    var toTop = document.createElement('button');
    toTop.type = 'button';
    toTop.className = 'back-to-top';
    toTop.setAttribute('aria-label', LOCALE === 'ko' ? '맨 위로' : 'Back to top');
    toTop.innerHTML =
      '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" ' +
      'stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' +
      '<path d="M12 19V5"/><path d="m5 12 7-7 7 7"/></svg>';
    toTop.addEventListener('click', function () {
      var reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
      window.scrollTo({ top: 0, behavior: reduced ? 'auto' : 'smooth' });
    });
    document.body.appendChild(toTop);

    var ticking = false;
    return function updateReadingControls() {
      if (ticking) return;
      ticking = true;
      window.requestAnimationFrame(function () {
        ticking = false;
        var scrollable = document.documentElement.scrollHeight - window.innerHeight;
        var ratio = scrollable > 0 ? window.scrollY / scrollable : 0;
        fill.style.width = Math.min(100, Math.max(0, ratio * 100)) + '%';
        toTop.classList.toggle('visible', window.scrollY > 600);
      });
    };
  }

  // --- Post body rendering (post pages only) ---
  //
  // build.js has already put the title, date, reading time and prev/next in
  // the served HTML, so all that is left is to fetch the markdown and render
  // it into #writing-content. The page frame is real HTML; only the body is
  // client-rendered, which is why the markdown pipeline still lives here.

  if (POST) {
    updateReadingControls = setupReadingControls();

    var writingContent = document.getElementById('writing-content');

    if (writingContent) {
      writingContent.innerHTML = '<p class="writing-loading">' + escapeHtml(t('loading')) + '</p>';
      Promise.all([
        ensurePostLibs(),
        // Leading '/' resolves from the site root: POST.file is a repo-relative
        // path like "posts/CS 61B/week 1.md" and this page lives two levels
        // deep at /p/<slug>/.
        fetch(encodeURI('/' + POST.file)).then(function (res) {
          if (!res.ok) throw new Error('Failed to load ' + POST.file + ' (HTTP ' + res.status + ')');
          return res.text();
        })
      ])
        .then(function (arr) {
          var md = arr[1];
          // Same root-relative reasoning as the fetch above: embeds (![[...]])
          // resolve against this baseDir.
          var baseDir = '/' + POST.file.substring(0, POST.file.lastIndexOf('/') + 1);
          var result = preprocessObsidian(md, baseDir);
          var html = marked.parse(result.md);
          html = restoreFootnotes(html, result.footnotes);
          html = restoreMathAndMarks(html, result.mathStore);
          writingContent.innerHTML = '<div class="writing-body">' + html + '</div>';

          var body = writingContent.querySelector('.writing-body');
          if (!body) return;
          dropRedundantLeadingElements(body);
          assignHeadingIds(body);
          transformCallouts(body);
          renderMath(body);
          if (typeof hljs !== 'undefined') {
            body.querySelectorAll('pre code').forEach(function (el) {
              hljs.highlightElement(el);
            });
          }
          wrapTables(body);
          enhanceImages(body);
          addCopyButtons(body);
          buildTOC(body);
          // After buildTOC — it reads h.textContent for the TOC labels, and
          // the anchor would otherwise show up as a "#" on every entry.
          addHeadingAnchors(body);
          setupInternalLinks(body);
          setupFootnotePreviews(body);
          // The headings this may target only exist now, at the end of the
          // pipeline; see scrollToHashOnLoad.
          scrollToHashOnLoad();
          if (updateReadingControls) updateReadingControls();
        })
        .catch(function (err) {
          writingContent.innerHTML = '<p class="writing-error">' + escapeHtml(t('loadError')) + '</p>';
          // Surface the cause: a missing markdown file and an unreachable CDN
          // look identical to the reader otherwise.
          console.error('Post render failed:', err);
        });
    }
  }

  // --- Post list (landing pages only) ---

  if (!POST && typeof writings !== 'undefined') {
    var writingsList = document.getElementById('writings-list');

    if (writingsList) {
      var catLabels = (typeof writingCategories !== 'undefined') ? writingCategories : {};

      var sortedWritings = writings.slice().sort(function (a, b) {
        return new Date(b.date) - new Date(a.date);
      });

      var catCounts = {};
      sortedWritings.forEach(function (w) {
        if (w.category) catCounts[w.category] = (catCounts[w.category] || 0) + 1;
      });

      // The full-text index is ~350 KB — far larger than everything else on
      // the page combined — and most visitors never search. So it is fetched
      // the first time the search box is touched rather than loaded up front.
      // Until it arrives, matchesSearch falls back to title + summary.
      var searchIndexData = null;
      var searchIndexPromise = null;

      function ensureSearchIndex() {
        if (searchIndexPromise) return searchIndexPromise;
        searchIndexPromise = fetch('/js/search-index.json')
          .then(function (res) {
            if (!res.ok) throw new Error('HTTP ' + res.status);
            return res.json();
          })
          .then(function (data) {
            searchIndexData = data;
            // A query may already have been typed while this was in flight.
            applyFilters();
          })
          .catch(function (err) {
            // Not fatal: search keeps working against titles and summaries.
            console.error('Search index unavailable, falling back to titles and summaries:', err);
          });
        return searchIndexPromise;
      }

      var filtersHtml = '<div class="writings-search-wrap">' +
        '<input type="search" id="writings-search" class="writings-search-input" placeholder="' + escapeAttr(t('searchPlaceholder')) + '" aria-label="' + escapeAttr(t('searchAria')) + '">' +
        '</div>' +
        '<div class="writings-filters">' +
        '<button class="filter-btn active" type="button" aria-pressed="true" data-category="all">' + escapeHtml(t('all')) + ' (' + sortedWritings.length + ')</button>';
      Object.keys(catCounts).forEach(function (cat) {
        filtersHtml += '<button class="filter-btn" type="button" aria-pressed="false" data-category="' + escapeAttr(cat) + '">' +
          escapeHtml(catLabels[cat] || cat) + ' (' + catCounts[cat] + ')</button>';
      });
      filtersHtml += '</div>';
      filtersHtml += '<p id="writings-no-results" class="writings-no-results" role="status" aria-live="polite" style="display:none">' + escapeHtml(t('noResults')) + '</p>';
      writingsList.insertAdjacentHTML('beforebegin', filtersHtml);

      var POSTS_VISIBLE_INITIAL = 5;
      var POSTS_VISIBLE_STEP = 5;
      var visibleCount = POSTS_VISIBLE_INITIAL;

      // Real anchors, not <article role="button">: middle-click and
      // open-in-new-tab work, keyboard activation is the browser's job, and
      // crawlers get 65 internal links to follow.
      writingsList.innerHTML = sortedWritings
        .map(function (w, i) {
          var catTag = catLabels[w.category] || w.category || '';
          return (
            '<a class="writing-card" href="/p/' + escapeAttr(encodeURIComponent(w.slug)) + '/"' +
            ' data-index="' + i + '" data-category="' + escapeAttr(w.category || '') + '">' +
            '<div class="writing-card-meta">' +
              '<time class="writing-card-date" datetime="' + escapeAttr(w.date || '') + '">' + escapeHtml(formatDate(w.date)) + '</time>' +
              (catTag ? '<span class="writing-card-tag">' + escapeHtml(catTag) + '</span>' : '') +
            '</div>' +
            '<h3 class="writing-card-title">' + escapeHtml(w.title) + '</h3>' +
            '<p class="writing-card-summary">' + escapeHtml(w.summary) + '</p>' +
            '<span class="writing-card-read">' + escapeHtml(t('readMore')) + '</span>' +
            '</a>'
          );
        })
        .join('');

      writingsList.insertAdjacentHTML('afterend',
        '<div id="writings-show-more-wrap" class="writings-show-more-wrap" style="display:none">' +
        '<button type="button" id="writings-show-more-btn" class="writings-show-more-btn">' + escapeHtml(t('showMore')) + '</button>' +
        '</div>');

      var searchInput = writingsList.parentElement.querySelector('#writings-search');
      var noResultsEl = writingsList.parentElement.querySelector('#writings-no-results');
      var showMoreWrap = writingsList.parentElement.querySelector('#writings-show-more-wrap');
      var showMoreBtn = writingsList.parentElement.querySelector('#writings-show-more-btn');

      function getSearchQuery() {
        return searchInput ? searchInput.value.trim().toLowerCase() : '';
      }

      function matchesSearch(w) {
        var q = getSearchQuery();
        if (!q) return true;
        var indexEntry = searchIndexData ? searchIndexData[w.slug] : null;
        var text = (w.title + ' ' + (indexEntry ? indexEntry.text : (w.summary || ''))).toLowerCase();
        return text.indexOf(q) !== -1;
      }

      function applyFilters() {
        var filtersEl = writingsList.parentElement.querySelector('.writings-filters');
        var activeBtn = filtersEl ? filtersEl.querySelector('.filter-btn.active') : null;
        var cat = (activeBtn && activeBtn.getAttribute('data-category')) || 'all';
        var matchingCards = [];
        writingsList.querySelectorAll('.writing-card').forEach(function (card) {
          var idx = parseInt(card.getAttribute('data-index'), 10);
          var w = sortedWritings[idx];
          var match = w && matchesSearch(w) && (cat === 'all' || (w.category || '') === cat);
          if (match) matchingCards.push(card);
        });
        var limit = Math.min(visibleCount, matchingCards.length);
        var visibleCards = matchingCards.slice(0, limit);
        writingsList.querySelectorAll('.writing-card').forEach(function (card) {
          card.style.display = visibleCards.indexOf(card) !== -1 ? '' : 'none';
        });
        if (noResultsEl) noResultsEl.style.display = matchingCards.length === 0 ? '' : 'none';
        if (showMoreWrap && showMoreBtn) {
          var remaining = matchingCards.length - limit;
          if (remaining > 0) {
            showMoreWrap.style.display = '';
            showMoreBtn.textContent = t('showMore') + ' (' + remaining + ')';
          } else {
            showMoreWrap.style.display = 'none';
          }
        }
      }

      // Changing what is being listed starts the count over: without this,
      // clicking "Show more" three times and then picking a category would
      // open that category at 20 posts instead of 5.
      function resetPagination() {
        visibleCount = POSTS_VISIBLE_INITIAL;
        applyFilters();
      }

      var filtersEl = writingsList.parentElement.querySelector('.writings-filters');
      if (filtersEl) {
        filtersEl.addEventListener('click', function (e) {
          var btn = e.target.closest('.filter-btn');
          if (!btn) return;
          filtersEl.querySelectorAll('.filter-btn').forEach(function (b) {
            b.classList.toggle('active', b === btn);
            b.setAttribute('aria-pressed', b === btn ? 'true' : 'false');
          });
          resetPagination();
        });
      }
      if (searchInput) {
        searchInput.addEventListener('focus', ensureSearchIndex);
        searchInput.addEventListener('input', function () {
          ensureSearchIndex();
          resetPagination();
        });
        searchInput.addEventListener('search', resetPagination);
      }
      if (showMoreBtn) {
        showMoreBtn.addEventListener('click', function () {
          visibleCount += POSTS_VISIBLE_STEP;
          applyFilters();
        });
      }

      applyFilters();
    }
  }

  // Render experiences timeline from experiences.js
  if (typeof experiences !== 'undefined') {
    const timeline = document.getElementById('experiences-timeline');
    if (timeline) {
      // Experience entries are not translated — see experiences.js.
      timeline.innerHTML = experiences
        .map(function (exp) {
          var bulletsHtml = (exp.bullets || [])
            .map(function (b) {
              return '<li>' + escapeHtml(b) + '</li>';
            })
            .join('');
          var typeLabel = exp.type === 'work' ? 'Experience' : 'Education';
          return (
            '<article class="timeline-item timeline-item--' + escapeAttr(exp.type) + '">' +
            '<div class="timeline-marker"></div>' +
            '<div class="timeline-content">' +
            '<span class="timeline-type">' + escapeHtml(typeLabel) + '</span>' +
            '<h3 class="timeline-title">' + escapeHtml(exp.title) + '</h3>' +
            '<p class="timeline-org">' + escapeHtml(exp.org) + '</p>' +
            '<p class="timeline-meta">' + escapeHtml(exp.period) + ' · ' + escapeHtml(exp.location) + '</p>' +
            '<ul class="timeline-bullets">' + bulletsHtml + '</ul>' +
            '</div>' +
            '</article>'
          );
        })
        .join('');
    }
  }

  function escapeHtml(text) {
    var div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
  }

  function escapeAttr(text) {
    return String(text)
      .replace(/&/g, '&amp;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
  }

  // --- Footer year ---
  // Computed instead of hardcoded so it never silently goes stale on Jan 1.
  var footerP = document.querySelector('.footer p');
  if (footerP) {
    footerP.textContent = footerP.textContent.replace(/©\s*\d{4}/, '© ' + new Date().getFullYear());
  }

  // --- Scroll-reveal entrance animation ---
  // Cards/timeline items/section titles fade + rise in the first time they
  // cross into the viewport. The .reveal class (which starts elements at
  // opacity:0) is only ever added here, in JS, after confirming
  // IntersectionObserver exists and the user hasn't asked for reduced
  // motion — so with JS disabled, or on that media query, everything is
  // simply visible immediately. Never hides content behind a JS dependency.
  if (
    typeof IntersectionObserver !== 'undefined' &&
    !(window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches)
  ) {
    var revealTargets = document.querySelectorAll(
      '.card, .writing-card, .timeline-item, .section-title'
    );
    var revealObserver = new IntersectionObserver(
      function (entries) {
        entries.forEach(function (entry) {
          if (!entry.isIntersecting) return;
          entry.target.classList.add('in-view');
          revealObserver.unobserve(entry.target);
        });
      },
      { threshold: 0.1, rootMargin: '0px 0px -40px 0px' }
    );
    revealTargets.forEach(function (el) {
      el.classList.add('reveal');
      revealObserver.observe(el);
    });
  }
})();
