const writingCategories = {
  "econometrics": "Econometrics",
  "r-programming": "R Programming"
};

const writings = [
  {
    slug: "intro-to-econometrics",
    title: "Introduction to Econometrics",
    date: "2026-01-20",
    summary: "Types of econometric questions — descriptive, causal, and forecasting. Covers selection bias, the counterfactual framework, and a taxonomy of economic data types.",
    file: "posts/ENVECON C118/ENVECON C118 1.20.md",
    category: "econometrics",
  },
  {
    slug: "random-variables-probability",
    title: "Random Variables & Probability Foundations",
    date: "2026-01-22",
    summary: "Probability distributions, CDF, PMF, PDF, joint and conditional distributions. Includes a practical guide to data visualization with R and ggplot2.",
    file: "posts/ENVECON C118/ENVECON C118 1.22.md",
    category: "econometrics",
  },
  {
    slug: "conditional-expectations-lie",
    title: "Conditional Expectations & the Law of Iterated Expectations",
    date: "2026-01-27",
    summary: "Joint distributions, independence, covariance, correlation, and the Law of Iterated Expectations (LIE). Plus a hands-on R tutorial on dplyr data transformation.",
    file: "posts/ENVECON C118/ENVECON C118 1.27.md",
    category: "econometrics",
  },
  {
    slug: "estimators-potential-outcomes",
    title: "Estimators & the Potential Outcomes Framework",
    date: "2026-01-29",
    summary: "Parameters vs. estimands vs. estimators. The potential outcomes framework, Average Treatment Effect (ATE), selection bias, and identification through randomization.",
    file: "posts/ENVECON C118/ENVECON C118 1.29.md",
    category: "econometrics",
  },
  {
    slug: "r-vectors-factors",
    title: "R Data Structures: Vectors & Factors",
    date: "2026-02-02",
    summary: "Atomic vectors, type coercion, vectorization, recycling rules, indexing patterns, and factors in R. A comprehensive foundation for data manipulation.",
    file: "posts/STAT 33B/STAT 33B 2.2.md",
    category: "r-programming",
  },
  {
    slug: "ate-regression",
    title: "Average Treatment Effects & Regression",
    date: "2026-02-03",
    summary: "ATE derivation under randomization, statistical inference basics (i.i.d. sampling, unbiasedness), and the regression framework — conditional expectation function and OLS.",
    file: "posts/ENVECON C118/ENVECON C118 2.3.md",
    category: "econometrics",
  },
  {
    slug: "simple-linear-regression",
    title: "Simple Linear Regression & OLS",
    date: "2026-02-05",
    summary: "The simple linear regression model, OLS derivation, error term assumptions, residuals, fitted values, R-squared, and why correlation doesn't imply causation.",
    file: "posts/ENVECON C118/ENVECON C118 2.5.md",
    category: "econometrics",
  },
  {
    slug: "functional-forms-regression",
    title: "Functional Forms in Regression",
    date: "2026-02-07",
    summary: "Translating economic models to econometric specifications. Practical guide to linear, log-linear, linear-log, and log-log models with worked examples and elasticity interpretation.",
    file: "posts/ENVECON C118/ENVECON C118 Discussion 1.md",
    category: "econometrics",
  },
  {
    slug: "r-matrices-lists",
    title: "Matrices, Lists & the apply() Family in R",
    date: "2026-02-09",
    summary: "Matrix creation and algebra, the apply() function, lists with $, [], [[]] indexing, and the tradeoffs between atomic and non-atomic data structures in R.",
    file: "posts/STAT 33B/STAT 33B 2.9.md",
    category: "r-programming",
  },
  {
    slug: "regression-transformations",
    title: "Regression Transformations & Log Models",
    date: "2026-02-10",
    summary: "Log-linear, linear-log, and log-log transformations with elasticity interpretation. The five classical assumptions of linear regression and their implications.",
    file: "posts/ENVECON C118/ENVECON C118 2.10.md",
    category: "econometrics",
  },
  {
    slug: "multivariable-regression",
    title: "Multivariable Regression",
    date: "2026-02-12",
    summary: "Why simple regression falls short: confounding variables and omitted factors. Ceteris paribus interpretation, the no-perfect-collinearity assumption, and reducing estimator variance.",
    file: "posts/ENVECON C118/ENVECON C118 2.12.md",
    category: "econometrics",
  },
  {
    slug: "ovb-hypothesis-testing",
    title: "Omitted Variable Bias & Hypothesis Testing",
    date: "2026-02-17",
    summary: "The OVB formula (Bias = beta_2 x rho) and how to determine bias direction. Introduction to the CLT, test statistics, p-values, and confidence intervals.",
    file: "posts/ENVECON C118/ENVECON C118 2.17.md",
    category: "econometrics",
  },
  {
    slug: "confidence-intervals-t-distribution",
    title: "Confidence Intervals & the t-Distribution",
    date: "2026-02-19",
    summary: "OVB bounds for bounding causal effects. Confidence intervals using the t-distribution, one-sided vs. two-sided tests, and comparing two population means.",
    file: "posts/ENVECON C118/ENVECON C118 2.19.md",
    category: "econometrics",
  },
  {
    slug: "r-data-import-frames",
    title: "Importing Data & Data Frames in R",
    date: "2026-02-23",
    summary: "Reading CSV, TSV, and fixed-width files with read.table() and read.csv(). Data frame structure, bracket and dollar subsetting, and conditional data manipulation.",
    file: "posts/STAT 33B/STAT 33B 2.23.md",
    category: "r-programming",
  },
  {
    slug: "rcts-compliance-ftest",
    title: "RCTs, Compliance & the F-test",
    date: "2026-02-24",
    summary: "How RCTs solve OVB through randomization. ITT, ATT, and LATE under non-compliance. Sampling distributions of OLS estimators, the 5-step hypothesis testing procedure, and the F-test.",
    file: "posts/ENVECON C118/ENVECON C118 2.24.md",
    category: "econometrics",
  },
  {
    slug: "statistical-inference-pvalues",
    title: "Statistical Inference: p-values & Common Mistakes",
    date: "2026-02-26",
    summary: "z-statistics vs. t-statistics, the t-statistic as 'number of standard errors from the null,' p-value interpretation, confidence interval construction, and common hypothesis testing pitfalls.",
    file: "posts/ENVECON C118/ENVECON C118 2.26.md",
    category: "econometrics",
  },
  {
    slug: "r-tidyverse-dplyr",
    title: "Tidyverse & dplyr Fundamentals",
    date: "2026-03-03",
    summary: "The tidyverse ecosystem and core dplyr verbs — filter, select, mutate, group_by, summarise. Tibbles vs. data frames and the pipe operator.",
    file: "posts/STAT 33B/STAT 33B 3.3.md",
    category: "r-programming",
  },
  {
    slug: "r-fundamentals-review",
    title: "R Fundamentals: A Comprehensive Review",
    date: "2026-03-07",
    summary: "Atomic vs. non-atomic objects, vectors, factors, matrices, lists, and data frames — all essential R data structures and their subsetting patterns in one reference.",
    file: "posts/STAT 33B/STAT33B Midterm.md",
    category: "r-programming",
  },
  {
    slug: "r-ggplot2-visualization",
    title: "Data Visualization with ggplot2",
    date: "2026-03-09",
    summary: "The layered grammar of graphics — geoms, aesthetics, mappings vs. settings, scales, themes, and practical visualization examples with ggplot2.",
    file: "posts/STAT 33B/STAT 33B 3.9.md",
    category: "r-programming",
  },
  {
    slug: "ftest-hedonic-regression",
    title: "F-test, Hedonic Regression & Adjusted R-squared",
    date: "2026-03-10",
    summary: "Testing joint significance with the F-test and F-distribution. Hedonic regression for valuing product attributes, and the adjusted R-squared as a model comparison tool.",
    file: "posts/ENVECON C118/ENVECON C118 3.10.md",
    category: "econometrics",
  },
];
