#!/usr/bin/env node
//
// Generates everything that is derived from the post list:
//
//   p/<slug>/index.html   one real page per post (crawlable, shareable)
//   js/search-index.json  full-text index, fetched on demand by main.js
//   sitemap.xml, feed.xml via feeds.js
//
// Deliberately reads only what is committed to this repo — js/writings.js and
// posts/**/*.md — and never Ricky's Obsidian vault. sync.js owns the vault and
// writes js/writings.js + posts/; this file turns that into the published site.
// Keeping the two separate means the site can be rebuilt from a fresh clone,
// by CI or by anyone, without the vault being present.
//
// Runnable standalone (`node build.js`) or via sync.js, which calls build()
// after it has refreshed js/writings.js.

const fs = require('fs');
const path = require('path');
const { writeFeeds } = require('./feeds');

const SITE_URL = 'https://uichan-lee.github.io';
const AUTHOR = 'Uichan Lee';

const ROOT = __dirname;
const WRITINGS_JS = path.join(ROOT, 'js', 'writings.js');
const SEARCH_INDEX_JSON = path.join(ROOT, 'js', 'search-index.json');
const PAGES_DIR = path.join(ROOT, 'p');

// ─── Helpers ────────────────────────────────────────────────────────────────

function xmlEscape(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** JSON embedded in <script> must not contain a literal </script> or a raw <. */
function jsonForScript(value) {
  return JSON.stringify(value).replace(/</g, '\\u003c');
}

/**
 * Read js/writings.js and hand back the two globals it declares.
 * That file is generated by sync.js as plain `const writings = [...]`, so it
 * is evaluated rather than parsed. It is our own build output, not input from
 * anywhere untrusted.
 */
function loadWritings() {
  const code = fs.readFileSync(WRITINGS_JS, 'utf-8');
  const out = {};
  new Function(
    'out',
    code + '\nout.writings = writings; out.writingCategories = writingCategories;'
  )(out);
  return out;
}

/** Strip markdown to plain text, for the search index and the word count. */
function stripMarkdownToPlainText(content) {
  const text = content
    .replace(/^---[\s\S]*?^---\s*/m, '')
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/!\[\[[^\]]*\]\]/g, ' ')
    .replace(/!\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/\*\*?|__?/g, '')
    .replace(/^#{1,6}\s+/gm, ' ')
    .replace(/^\s*[-*]\s+/gm, ' ')
    .replace(/^\s*\d+\.\s+/gm, ' ')
    .replace(/^\s*\|.*\|\s*$/gm, ' ')
    .replace(/\$\$[\s\S]*?\$\$/g, ' ')
    .replace(/\$[^$]+\$/g, ' ')
    .replace(/\n+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  return text.length > 30000 ? text.slice(0, 30000) : text;
}

const CJK_RE = /[ㄱ-힝一-鿿぀-ヿ]/g;

/**
 * Minutes to read. Latin text is counted in words at 200 wpm; Korean and other
 * CJK is counted in characters at 500 cpm, because whitespace-splitting Hangul
 * badly undercounts it (these posts are a mix of both).
 */
function readingTimeMinutes(plain) {
  const cjk = (plain.match(CJK_RE) || []).length;
  const latin = plain.replace(CJK_RE, ' ').split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.ceil(latin / 200 + cjk / 500));
}

function formatDisplayDate(dateStr) {
  if (!dateStr) return '';
  const d = new Date(dateStr + 'T00:00:00Z');
  if (Number.isNaN(d.getTime())) return '';
  return d.toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC',
  });
}

/** Slugs contain Hangul, so every generated href has to be percent-encoded. */
function postUrl(slug) {
  return '/p/' + encodeURIComponent(slug) + '/';
}

// ─── Page template ──────────────────────────────────────────────────────────

// Header and footer are duplicated from index.html on purpose: this repo has no
// templating layer, and generating them here is what keeps the 65 post pages in
// sync with each other. If index.html's header changes, change it here too.
function renderHeader() {
  return [
    '  <a class="skip-link" href="#main">Skip to content</a>',
    '  <header class="header">',
    '    <a href="/" class="logo">Uichan Lee</a>',
    '    <div class="header-right">',
    '      <nav class="nav" id="primary-nav">',
    '        <a href="/#home" class="nav-link">Home</a>',
    '        <a href="/#projects" class="nav-link">Projects</a>',
    '        <a href="/#writings" class="nav-link">Posts</a>',
    '        <a href="/#experiences" class="nav-link">Experiences</a>',
    '      </nav>',
    '      <button id="theme-toggle" class="theme-toggle" type="button" aria-label="Toggle dark mode">',
    '        <svg class="icon-moon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>',
    '        <svg class="icon-sun" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>',
    '      </button>',
    '      <button id="nav-toggle" class="nav-toggle" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="primary-nav">',
    '        <svg class="icon-menu" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg>',
    '        <svg class="icon-close" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>',
    '      </button>',
    '    </div>',
    '  </header>',
  ].join('\n');
}

function renderFooter() {
  return [
    '  <footer class="footer">',
    '    <p>© 2026 Uichan Lee</p>',
    '  </footer>',
  ].join('\n');
}

function renderPostNav(prev, next) {
  if (!prev && !next) return '';
  const parts = ['      <nav class="post-nav" aria-label="More posts">'];
  if (prev) {
    parts.push(
      '        <a class="post-nav-link post-nav-prev" href="' + xmlEscape(postUrl(prev.slug)) + '" rel="prev">' +
        '<span class="post-nav-label">← Older</span>' +
        '<span class="post-nav-title">' + xmlEscape(prev.title) + '</span></a>'
    );
  }
  if (next) {
    parts.push(
      '        <a class="post-nav-link post-nav-next" href="' + xmlEscape(postUrl(next.slug)) + '" rel="next">' +
        '<span class="post-nav-label">Newer →</span>' +
        '<span class="post-nav-title">' + xmlEscape(next.title) + '</span></a>'
    );
  }
  parts.push('      </nav>');
  return parts.join('\n');
}

function renderPostPage(post, categoryLabel, prev, next) {
  const url = SITE_URL + postUrl(post.slug);
  const pageTitle = post.title + ' | ' + AUTHOR;
  const description = post.summary || (post.title + ' — notes by ' + AUTHOR + '.');

  // Structured data so the post is eligible for rich results. mainEntityOfPage
  // points back at this page's canonical URL.
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.title,
    description: description,
    datePublished: post.date,
    dateModified: post.date,
    author: { '@type': 'Person', name: AUTHOR, url: SITE_URL + '/' },
    publisher: { '@type': 'Person', name: AUTHOR, url: SITE_URL + '/' },
    mainEntityOfPage: { '@type': 'WebPage', '@id': url },
    inLanguage: 'en',
    isPartOf: { '@type': 'Blog', name: AUTHOR + ' — Posts', url: SITE_URL + '/#writings' },
  };
  if (categoryLabel) jsonLd.articleSection = categoryLabel;

  // Only what main.js needs to fetch and render the markdown body.
  const bootstrap = {
    slug: post.slug,
    file: post.file,
    title: post.title,
    date: post.date,
    category: post.category || '',
  };

  const metaLine =
    '        <div class="post-meta">' +
    '<time datetime="' + xmlEscape(post.date) + '">' + xmlEscape(formatDisplayDate(post.date)) + '</time>' +
    (categoryLabel ? '<span class="writing-card-tag">' + xmlEscape(categoryLabel) + '</span>' : '') +
    '<span class="post-reading-time">' + post.readingTime + ' min read</span>' +
    '</div>';

  return [
    '<!-- Generated by build.js from js/writings.js. Do not edit by hand. -->',
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="UTF-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '  <title>' + xmlEscape(pageTitle) + '</title>',
    '  <meta name="description" content="' + xmlEscape(description) + '">',
    '  <meta name="author" content="' + AUTHOR + '">',
    '  <link rel="canonical" href="' + xmlEscape(url) + '">',
    '  <link rel="alternate" type="application/rss+xml" title="Uichan Lee — Posts" href="/feed.xml">',
    '  <meta name="theme-color" content="#f8fafc" media="(prefers-color-scheme: light)">',
    '  <meta name="theme-color" content="#0f172a" media="(prefers-color-scheme: dark)">',
    '  <link rel="icon" href="data:image/svg+xml,<svg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 100 100\'><rect width=\'100\' height=\'100\' rx=\'22\' fill=\'%230f172a\'/><text x=\'50\' y=\'70\' font-family=\'DM Sans, sans-serif\' font-size=\'54\' font-weight=\'700\' fill=\'%23ffffff\' text-anchor=\'middle\'>UL</text></svg>">',
    '  <meta property="og:type" content="article">',
    '  <meta property="og:url" content="' + xmlEscape(url) + '">',
    '  <meta property="og:title" content="' + xmlEscape(post.title) + '">',
    '  <meta property="og:description" content="' + xmlEscape(description) + '">',
    '  <meta property="og:image" content="' + SITE_URL + '/assets/og-image.jpg">',
    '  <meta property="og:image:width" content="1200">',
    '  <meta property="og:image:height" content="630">',
    '  <meta property="og:locale" content="en_US">',
    '  <meta property="article:published_time" content="' + xmlEscape(post.date) + '">',
    '  <meta property="article:author" content="' + AUTHOR + '">',
    '  <meta name="twitter:card" content="summary_large_image">',
    '  <meta name="twitter:title" content="' + xmlEscape(post.title) + '">',
    '  <meta name="twitter:description" content="' + xmlEscape(description) + '">',
    '  <meta name="twitter:image" content="' + SITE_URL + '/assets/og-image.jpg">',
    '  <link rel="preconnect" href="https://fonts.googleapis.com">',
    '  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    '  <link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin>',
    '  <link rel="preconnect" href="https://cdnjs.cloudflare.com" crossorigin>',
    '  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;1,9..40,400&display=swap" rel="stylesheet">',
    '  <link rel="stylesheet" href="/css/style.css">',
    '  <script type="application/ld+json">' + jsonForScript(jsonLd) + '</script>',
    '  <!-- marked / KaTeX / highlight.js load on demand once the body renders (see js/main.js) -->',
    '  <script>(function(){var t=localStorage.getItem(\'theme\'),d=t===\'dark\'||(t!==\'light\'&&window.matchMedia(\'(prefers-color-scheme: dark)\').matches);document.documentElement.setAttribute(\'data-theme\',d?\'dark\':\'light\');})();</script>',
    '</head>',
    '<body>',
    renderHeader(),
    '',
    '  <main id="main">',
    '    <section class="section section-writings section-post">',
    '      <div class="post-header">',
    '        <a class="writing-back-btn" href="/#writings">&larr; Back to list</a>',
    metaLine,
    '        <h1 class="post-title">' + xmlEscape(post.title) + '</h1>',
    (post.summary ? '        <p class="post-summary">' + xmlEscape(post.summary) + '</p>' : ''),
    '      </div>',
    '      <div id="writing-toc-inline" class="writing-toc-inline" aria-label="Table of contents"></div>',
    '      <article id="writing-content" class="writing-content"></article>',
    renderPostNav(prev, next),
    '    </section>',
    '    <nav id="writing-toc" class="writing-toc" aria-label="Table of contents"></nav>',
    '  </main>',
    '',
    renderFooter(),
    '',
    '  <script>window.__POST__ = ' + jsonForScript(bootstrap) + ';</script>',
    '  <script src="/js/main.js"></script>',
    '  <script data-goatcounter="https://uichan-portfolio.goatcounter.com/count"',
    '          async src="//gc.zgo.at/count.js"></script>',
    '</body>',
    '</html>',
    '',
  ].join('\n');
}

// ─── Main ───────────────────────────────────────────────────────────────────

function build() {
  const loaded = loadWritings();
  const writings = loaded.writings || [];
  const categories = loaded.writingCategories || {};

  // Same guard as sync.js uses for the feeds: a run that collected nothing
  // (js/writings.js missing or emptied) must never wipe the published pages.
  if (writings.length === 0) {
    console.log('  skip build: js/writings.js lists no posts');
    return 0;
  }

  // Newest first. Index i-1 is the newer neighbour, i+1 the older one.
  const posts = writings.slice().sort(function (a, b) {
    return String(b.date).localeCompare(String(a.date));
  });

  const searchIndex = {};
  posts.forEach(function (post) {
    const mdPath = path.join(ROOT, post.file);
    let plain = '';
    if (fs.existsSync(mdPath)) {
      plain = stripMarkdownToPlainText(fs.readFileSync(mdPath, 'utf-8'));
    } else {
      console.warn('  warning: markdown missing for ' + post.slug + ' (' + post.file + ')');
    }
    post.readingTime = readingTimeMinutes(plain);
    searchIndex[post.slug] = { title: post.title, text: plain };
  });

  fs.rmSync(PAGES_DIR, { recursive: true, force: true });
  fs.mkdirSync(PAGES_DIR, { recursive: true });

  posts.forEach(function (post, i) {
    const dir = path.join(PAGES_DIR, post.slug);
    fs.mkdirSync(dir, { recursive: true });
    const html = renderPostPage(
      post,
      categories[post.category] || post.category || '',
      posts[i + 1] || null, // older
      posts[i - 1] || null  // newer
    );
    fs.writeFileSync(path.join(dir, 'index.html'), html, 'utf-8');
  });
  console.log('  p/<slug>/index.html: ' + posts.length + ' pages written');

  fs.writeFileSync(SEARCH_INDEX_JSON, JSON.stringify(searchIndex), 'utf-8');
  console.log('  search-index.json: ' + Object.keys(searchIndex).length + ' entries');

  writeFeeds(ROOT, SITE_URL, posts, categories);
  console.log('  sitemap.xml + feed.xml written');

  return posts.length;
}

module.exports = { build, stripMarkdownToPlainText, readingTimeMinutes, postUrl };

if (require.main === module) {
  console.log('Building post pages from js/writings.js...\n');
  build();
  console.log('\nDone.');
}
